name = "resekassa"
main = "worker.js"
compatibility_date = "2026-01-01"

# KV-namespace för resedata. Byt ut id:t mot ditt egna (se README, steg 2).
[[kv_namespaces]]
binding = "TRIPS"
id = "62a6d9d9eb1d4a68af9219d6fdbebf84"
